$image = /home/mikhail/Pictures/Wallpaper/Everforest/waterfall.png

$background = rgba(2b292dff)

$error = rgba(ffb8afff)

$error_container = rgba(f83b34ff)

$inverse_on_surface = rgba(454447ff)

$inverse_primary = rgba(615f71ff)

$inverse_surface = rgba(e7e3e5ff)

$on_background = rgba(e7e3e5ff)

$on_error = rgba(8e0003ff)

$on_error_container = rgba(ffffffff)

$on_primary = rgba(333346ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(2d2d43ff)

$on_primary_fixed_variant = rgba(505062ff)

$on_secondary = rgba(343441ff)

$on_secondary_container = rgba(ffffffff)

$on_secondary_fixed = rgba(2f2f3dff)

$on_secondary_fixed_variant = rgba(52505cff)

$on_surface = rgba(f8f3f6ff)

$on_surface_variant = rgba(cecaccff)

$on_tertiary = rgba(31314dff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(2a2c4bff)

$on_tertiary_fixed_variant = rgba(4e4e68ff)

$outline = rgba(aaa8aaff)

$outline_variant = rgba(838182ff)

$primary = rgba(cccadbff)

$primary_container = rgba(807f90ff)

$primary_fixed = rgba(e5e2f4ff)

$primary_fixed_dim = rgba(cccadbff)

$scrim = rgba(000000ff)

$secondary = rgba(cdcad5ff)

$secondary_container = rgba(82808bff)

$secondary_fixed = rgba(e6e3eeff)

$secondary_fixed_dim = rgba(cdcad5ff)

$shadow = rgba(000000ff)

$source_color = rgba(7c7c9dff)

$surface = rgba(2b292dff)

$surface_bright = rgba(545154ff)

$surface_container = rgba(3a393cff)

$surface_container_high = rgba(444344ff)

$surface_container_highest = rgba(4e4d4eff)

$surface_container_low = rgba(333135ff)

$surface_container_lowest = rgba(212125ff)

$surface_dim = rgba(2b292dff)

$surface_tint = rgba(cccadbff)

$surface_variant = rgba(59585aff)

$tertiary = rgba(cac8e2ff)

$tertiary_container = rgba(7f7e96ff)

$tertiary_fixed = rgba(e4e2fbff)

$tertiary_fixed_dim = rgba(cac8e2ff)

