#   _____ __ __ _____ _____ __    _____ _____ _____ 
#  |  |  |  |  |  _  | __  |  |  |     |     |  |  |
#  |     |_   _|   __|    -|  |__|  |  |   --|    -|
#  |__|__| |_| |__|  |__|__|_____|_____|_____|__|__|
#                                                 
#  by Bina

source = ~/.config/hypr/colors.conf
general {
    hide_cursor = true
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = $HOME/.cache/current_wallpaper
	blur_passes = 2
}



# -- time --
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $primary
    font_size = 80
    font_family = JetBrains Mono ExtraBold
    position = 0, 100
    halign = center
    valign = center
}

# -- greeting --
label {
    monitor =
    text = Welcome $USER 
    color = $on_surface_variant
    font_size = 20
    font_family = JetBrains Mono 
    position = 0, 0
    halign = center
    valign = center
}

# -- password input --
input-field {
    monitor =
    size = 230, 40
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    inner_color = $surface_container       # fully transparent
    font_color = $on_surface
    fade_on_empty = true
    fade_timeout = 0
    placeholder_text =                  # empty, no hint text
    fail_color = $error
    hide_input = false
    position = 0, -150
    halign = center
    valign = center
}
