general {
    lock_cmd = pidof hyprlock || hyprlock       # lock before sleep
    before_sleep_cmd = loginctl lock-session     # lock on suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn screen on after wake
}

listener {
    timeout = 600                                # 5 min → lock screen
    on-timeout = hyprlock
}

listener {
    timeout = 660                                # 11 min → turn off display
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900                                # 15 min → suspend
    on-timeout = systemctl suspend
}
