#!/usr/bin/env bash
dir="$HOME/.config/rofi/launchers/type-1"
theme='style-5'

cliphist list | rofi \
    -dmenu \
    -p "Clipboard" \
    -theme ${dir}/${theme}.rasi \
    | cliphist decode | wl-copy
