general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    
    col.active_border = rgba(808080ff) $primary 20deg
    col.inactive_border = $outline_variant
    
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
decoration {
    rounding = 10
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0
    
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = $shadow
    }
    
    blur {
      enabled = true
      size = 4
      passes = 1
      ignore_opacity = true

      noise = 0.03
      contrast = 1.0
      brightness = 1

      xray = false
      new_optimizations = true
    }

}
