# ~/.config/hypr/modules/input.conf

input {
    kb_layout = us,ru
	kb_options = caps:escape,grp:alt_shift_toggle
	
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = true
        tap-and-drag = true
        disable_while_typing = true
        scroll_factor = 0.5        # slow scroll down if needed
    }
}

gestures {
    workspace_swipe_invert = false
    workspace_swipe_distance = 300

    gesture = 3, horizontal, workspace
}
