exec-once = waybar 
exec-once = firefox
exec-once = ~/.config/hypr/scripts/layout-notify.sh
exec-once = awww-daemon
exec-once = swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#cliphist daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
